### ISSUE TITLE
app armor ERROR 

### ISSUE THREAD

**Issue by denisght71** [DoliCloud/SellYourSaas#104] opened 2021-03-08 13:45 UTC
Hello,
When I configure AppArmor I get the error:
ERROR: Found reference to variable HOME, but is never declared

**Comment by eldy** [comment] 2021-03-09 10:26
When running which command do you have this ?

**Comment by eldy** [comment] 2021-05-28 12:18
Are you on ubuntu ?  You probably miss the file /etc/apparmor.d/tunables/home
that is provided by package   apparmor

**Comment by eldy** [comment] 2022-01-18 12:08
Closed as i can't reproduce on ubuntu 18.04 neither 20.04

**Closed by eldy** 2022-01-18 12:08 UTC
Labels: Bug
